ACK_HEADER = b'ACK' #ACKNOWLEDGEMENT HEADER
REQ_HEADER = b'REQ' #REQUEST HEADER
MOR_HEADER = b'MOR' #LAST FRAME HEADER
LAS_HEADER = b'LAS' #MORE FRAMES COMING HEADER
ENC_HEADER = b'KEY' #ENCRYPTION HEADER