ACK_HEADER = b'ACK' #ACKNOWLEDGEMENT HEADER
REQ_HEADER = b'REQ' #REQUEST HEADER
MOR_HEADER = b'MOR' #LAST FRAME HEADER
LAS_HEADER = b'LAS' #MORE FRAMES COMING HEADER
KEY_HEADER = b'KEY' #FRAME CONTAINS PUBLIC KEY
ENCRYPTED_REQ_HEADER = b'ERH'