ACK_HEADER = b'ACK' #SERVER ACKNOWLEDGEMENT OF REQUEST HEADER
REQ_HEADER = b'REQ' #FILE REQUEST HEADER
MOR_HEADER = b'MOR' #LAST FRAME HEADER
LAS_HEADER = b'LAS' #MORE FRAMES COMING HEADER
KEY_HEADER = b'KEY' #FRAME CONTAINS PUBLIC KEY HEADER
ENCRYPTED_REQ_HEADER = b'ERH' #SAME AS REQ HEADER BUT REQUEST IS ENCRYPTED
CFG_HEADER_1000 = b'CF1' #FRAME CONTAINS REQUESTED FILE NAME AND SETS SPLIT SIZE OF FILE FOR WORKER TO 1000 BYTES
CFG_HEADER_445 = b'CF0'  #FRAME CONTAINS REQUESTED FILE NAME AND SETS SPLIT SIZE OF FILE FOR WORKER TO 445 BYTES TO ENABLE ENCRYPTION